ddp:
    master_addr: "localhost"
    master_port: "29500"
    num_devices: 1

rlbench:
    task_name: "bottle_pickup"
    tasks: [gello_bottle1_rawtsdf,gello_bottle2_rawtsdf,gello_bottle3_rawtsdf,gello_bottle4_rawtsdf]
    demos: -1  # -1 = use all available demos per task (auto-detected)
    demo_path: /home/ceylanb/DreMa/drema_project/data/peract_ready/three_augmentations
    episode_length: 50
    cameras: [wrist,overhead]
    camera_resolution: [128, 128]
    scene_bounds: [0.15, -0.35, 0.20, 0.47, 0.30, 0.70]
    include_lang_goal_in_obs: True

replay:
    batch_size: 8
    timesteps: 1
    prioritisation: False
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/tmp/arm/replay' # only used when use_disk is True.
    max_parallel_processes: 32

framework:
    log_freq: 100
    save_freq: 100
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 100000
    gpu: 0
    env_gpu: 0
    logdir: /home/ceylanb/DreMa/drema_project/logs/peract_v2
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 0
    load_existing_weights: True
    num_weights_to_keep: 250 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5

defaults:
    - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
